name             'yum-cleanup'
maintainer       'RightScale Inc'
maintainer_email 'premium@rightscale.com'
license          'Apache 2.0'
description      'Installs/Configures yum-cleanup'
long_description 'Installs/Configures yum-cleanup'
version          '0.1.0'
